using Pkg

Pkg.add("StaticArrays")
Pkg.add("LinearAlgebra")
Pkg.add("Random")
Pkg.add("StatsBase")
Pkg.add("SparseArrays")
Pkg.add("Distributions")
Pkg.add("GridInterpolations")
Pkg.add("ParticleFilters")
Pkg.add("DataStructures")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("ArgParse")
Pkg.add("Plots")
Pkg.add("Dates")
